version: '3'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=evaadmin
      - MINIO_ROOT_PASSWORD=evaadmin123
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/:/data
    restart: unless-stopped

